name: agent_dart
description: |
  An agent library built for Internet Computer,
  a plugin package for dart and flutter apps.
  Developers can build ones to interact with Dfinity's blockchain directly.
version: 0.1.24+102
homepage: https://github.com/AstroxNetwork/agent_dart

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  archive: ^3.6.1
  args: ^2.3.1
  basic_utils: ^4.2.2
  bip32: ^2.0.0
  bip39: ^1.0.6
  cbor: ^4.1.0
  collection: ^1.16.0
  convert: ^3.0.1
  crypto: ^3.0.2
  ffi: ^1.2.1
  fixnum: ^1.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.4
  js: ^0.6.4
  meta: ^1.7.0
  path: ^1.8.1
  pinenacl: ^0.6.0
  pointycastle: ^3.6.0
  protobuf: ^2.0.1
  recase: ^4.0.0
  tuple: ^2.0.0
  typed_data: ^1.3.1
  uuid: ^3.0.6
  validators: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.astrox.agent_dart
        pluginClass: AgentDartPlugin
      ios:
        pluginClass: AgentDartPlugin
      linux:
        pluginClass: AgentDartPlugin
      macos:
        pluginClass: AgentDartPlugin
      windows:
        pluginClass: AgentDartPlugin
      web:
        pluginClass: AgentDartPlugin
        fileName: agent_dart_web.dart

false_secrets:
  - /test/fixture/*.pem
